In [53]:
import pandas as pd

df_euro_12 = pd.read_csv('../data_raw/euro12.csv')
df_euro_12

,Team,Goals,Shots on target,Shots off target,Shooting Accuracy,Yellow Cards,Red Cards
0,Spain,12,42,28,60%,11,0
1,Italy,6,34,25,58%,16,0
2,Germany,10,38,30,56%,10,1
3,Portugal,6,28,22,55%,12,0
4,England,5,26,24,54%,5,0
5,France,3,22,20,52%,6,0
6,Greece,5,18,16,50%,9,1
7,Russia,5,20,18,51%,6,1
8,Czech Republic,4,19,17,49%,7,0
9,Croatia,4,21,18,50%,9,0
10,Sweden,5,24,20,52%,8,0
11,Ukraine,2,15,14,48%,5,0
12,Poland,2,16,15,47%,7,0
13,Denmark,4,23,19,53%,6,0
14,Netherlands,2,17,16,46%,7,0
15,Ireland,1,10,12,45%,6,1

In [54]:
# IN gtr cột goals: 
print('In giá trị cột Goals: ')
df_euro_12.iloc[:,[0,1]]

In giá trị cột Goals:

              Team  Goals
0            Spain     12
1            Italy      6
2          Germany     10
3         Portugal      6
4          England      5
5           France      3
6           Greece      5
7           Russia      5
8   Czech Republic      4
9          Croatia      4
10          Sweden      5
11         Ukraine      2
12          Poland      2
13         Denmark      4
14     Netherlands      2
15         Ireland      1

In [55]:
# Có bao nhiêu đội tham gia Euro2012: 
print('Số đội tham gia Euro_2012: ',df_euro_12['Goals'].count())

Số đội tham gia Euro_2012:  16

In [56]:
# Tạo 1 dataframe mới có tên là  discipline chỉ chứa 3 cột 'Team', 'Yellow card', 'Red cards'
a = df_euro_12['Team']
b = df_euro_12['Yellow Cards']
c = df_euro_12['Red Cards']

discipline = pd.DataFrame(pd.concat([a, b, c],axis=1))
print(f'\nDataFrame Discipline: \n{discipline}')

DataFrame Discipline:
              Team  Yellow Cards  Red Cards
0            Spain            11          0
1            Italy            16          0
2          Germany            10          1
3         Portugal            12          0
4          England             5          0
5           France             6          0
6           Greece             9          1
7           Russia             6          1
8   Czech Republic             7          0
9          Croatia             9          0
10          Sweden             8          0
11         Ukraine             5          0
12          Poland             7          0
13         Denmark             6          0
14     Netherlands             7          0
15         Ireland             6          1

In [57]:
# Sắp xếp discipline giảm dần theo cột 'Red Cards': 

a = discipline['Red Cards']

b = a.sort_values()[::-1].index

df = pd.DataFrame(discipline, index=b)
print(f'\nSắp xếp discipline giảm dần theo Red Cards: \n{df}')

Sắp xếp discipline giảm dần theo Red Cards:
              Team  Yellow Cards  Red Cards
15         Ireland             6          1
2          Germany            10          1
6           Greece             9          1
7           Russia             6          1
11         Ukraine             5          0
14     Netherlands             7          0
13         Denmark             6          0
12          Poland             7          0
8   Czech Republic             7          0
9          Croatia             9          0
10          Sweden             8          0
5           France             6          0
4          England             5          0
3         Portugal            12          0
1            Italy            16          0
0            Spain            11          0

In [58]:
# Sắp xếp discipline giảm dần theo cột 'Yellow Cards': 

c = discipline['Yellow Cards']

d = c.sort_values()[::-1].index

df_1 = pd.DataFrame(discipline, index=d)
print(f'\nSắp xếp discipline giảm dần theo Yellow Cards: \n{df_1}')

Sắp xếp discipline giảm dần theo Yellow Cards:
              Team  Yellow Cards  Red Cards
1            Italy            16          0
3         Portugal            12          0
0            Spain            11          0
2          Germany            10          1
9          Croatia             9          0
6           Greece             9          1
10          Sweden             8          0
14     Netherlands             7          0
12          Poland             7          0
8   Czech Republic             7          0
15         Ireland             6          1
13         Denmark             6          0
5           France             6          0
7           Russia             6          1
11         Ukraine             5          0
4          England             5          0

In [59]:
# Tính trung bình Yellow Cards :
mean_yellow_cards = df_euro_12['Yellow Cards'].mean()


print(f'Trung bình thẻ vàng là : {mean_yellow_cards}/ 1 trận')

Trung bình thẻ vàng là : 8.125/ 1 trận

In [ ]:
mask_6_goals = df_euro_12.iloc[:,1] > 6
df_euro_12[mask_6_goals]

,Team,Goals,Shots on target,Shots off target,Shooting Accuracy,Yellow Cards,Red Cards
0,Spain,12,42,28,60%,11,0
2,Germany,10,38,30,56%,10,1

In [79]:
# In tên các đội mằ bắt đầu ghi hơn 6 bàn thắng: 
team_first_G = df_euro_12['Team'].str.startswith('G')
print('\nNhững đội bắt đầu bằng chữ G là: ')
print(df_euro_12[team_first_G])

Những đội bắt đầu bằng chữ G là:
      Team  Goals  Shots on target  Shots off target Shooting Accuracy  \
2  Germany     10               38                30               56%
6   Greece      5               18                16               50%

   Yellow Cards  Red Cards
2            10          1
6             9          1

In [81]:
# In tất cả trừ 3 cột cuối: 
df_euro_12.iloc[:,[0,1,2,3]]

              Team  Goals  Shots on target  Shots off target
0            Spain     12               42                28
1            Italy      6               34                25
2          Germany     10               38                30
3         Portugal      6               28                22
4          England      5               26                24
5           France      3               22                20
6           Greece      5               18                16
7           Russia      5               20                18
8   Czech Republic      4               19                17
9          Croatia      4               21                18
10          Sweden      5               24                20
11         Ukraine      2               15                14
12          Poland      2               16                15
13         Denmark      4               23                19
14     Netherlands      2               17                16
15         Ireland      1               10                12

In [104]:
f = df_euro_12.loc[[1,4,7], ['Team','Shooting Accuracy']]
f

      Team Shooting Accuracy
1    Italy               58%
4  England               54%
7   Russia               51%